import 'package:Tunein/components/bottomPanel.dart';
import 'package:Tunein/components/playing.dart';
import 'package:Tunein/plugins/nano.dart';
import 'package:Tunein/root.dart';
import 'package:Tunein/globals.dart';
import 'package:Tunein/services/layout.dart';
import 'package:Tunein/services/locator.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:simple